# Generated by Django 3.2.3 on 2021-05-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.IntegerField(max_length=20, verbose_name='Prontuário')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data_nasci', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1, verbose_name='Gênero')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('uf_rg', models.IntegerField(verbose_name='UF do CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('celular', models.CharField(max_length=12, unique=True, verbose_name='Nº telefone celular')),
                ('tel_fixo', models.CharField(max_length=12, verbose_name='Nº telefone fixo')),
                ('convenio', models.CharField(choices=[('SulAmérica', 'SulAmérica'), ('NotreDame Intermédica', 'NotreDame Intermédica'), ('Prevent Senior', 'Prevent Senior'), ('Assim Saúde', 'Assim Saúde'), ('Central Nacional Unimed (CNU)', 'Central Nacional Unimed (CNU)'), ('GreenLine Sistema de Saúde', 'GreenLine Sistema de Saúde'), ('Bradesco Seguros', 'Bradesco Seguros'), ('Hapvida Saúde', 'Hapvida Saúde')], max_length=50, verbose_name='Convênio')),
                ('carteira_convenio', models.IntegerField(verbose_name='Carteira convênio')),
                ('val_carteirinha', models.CharField(max_length=5, verbose_name='Validade Carteira')),
            ],
        ),
    ]
