# Generated by Django 3.2.3 on 2021-05-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.IntegerField(verbose_name='Prontuário'),
        ),
    ]
