# Generated by Django 3.2.3 on 2021-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0002_alter_paciente_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(max_length=50, verbose_name='Prontuário'),
        ),
    ]
