# Generated by Django 3.2.3 on 2021-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0003_alter_paciente_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=12, verbose_name='Nº telefone celular'),
        ),
    ]
