# Generated by Django 3.2.3 on 2021-06-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_patient', '0004_alter_paciente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='carteira_convenio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carteira convênio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº telefone celular'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(blank=True, choices=[('SulAmérica', 'SulAmérica'), ('NotreDame Intermédica', 'NotreDame Intermédica'), ('Prevent Senior', 'Prevent Senior'), ('Assim Saúde', 'Assim Saúde'), ('Central Nacional Unimed (CNU)', 'Central Nacional Unimed (CNU)'), ('GreenLine Sistema de Saúde', 'GreenLine Sistema de Saúde'), ('Bradesco Seguros', 'Bradesco Seguros'), ('Hapvida Saúde', 'Hapvida Saúde')], max_length=50, null=True, verbose_name='Convênio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nasci',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prontuário'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel_fixo',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nº telefone fixo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uf_rg',
            field=models.IntegerField(blank=True, null=True, verbose_name='UF do CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='val_carteirinha',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Validade Carteira'),
        ),
    ]
