# Generated by Django 3.2.3 on 2021-06-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_patient', '0005_auto_20210607_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctorName', models.CharField(max_length=50)),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_patient.paciente')),
            ],
        ),
    ]
